train:
  use_data_augmentation: false

  num_train_epochs: 5
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 4
  gradient_checkpointing: false

  eval_strategy: "steps"
  eval_steps: 10000
  logging_strategy: "steps"
  logging_steps: 100
  report_to: "none"
  save_strategy: "steps"
  save_steps: 500
  save_total_limit: 3

  optim: "paged_adamw_8bit"
  learning_rate: 5e-5
  max_grad_norm: 1.0
  lr_scheduler_type: "linear"
  warmup_ratio: 0.05

  fp16: true

  resume_from_checkpoint: null

  patience: 3
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  load_best_model_at_end: true
