defaults:
  - dataset
  - train
  - _self_

# Define the root workspace directory
# can be used for kubernetes
workspace: /home/top321902/code/intro_dl/term_project
cache_dir: null

# Paths based on workspace
dataset: ${workspace}/dataset
artifacts_dir: ${workspace}/skeleton/artifacts
evaluation_dir: ${workspace}/skeleton/evaluation

# name of the training e.g. train-qwen4b-rank8
# all artifacts from this train will be saved in ${artifacts_dir}/${train_name}
# if not set, train_name will be `train-<timestamp>`
train_name: null 
model_id: Qwen3/Qwen3-4B

